version: '3.8'

services:
  go-app:
    build:
      context: ./go-app
    ports:
      - "8000:8000"

  nextjs-app:
    build:
      context: ./nextjs-app
    ports:
      - "3000:3000"

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
